# Generated by Django 5.0.7 on 2024-10-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='requests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('them', models.CharField(max_length=30)),
                ('requesttype', models.CharField(choices=[('S', 'Обслуживание'), ('I', 'Установка оборудования'), ('O', 'Другой  вариант')], max_length=30)),
                ('priority', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('responsibleemployee', models.CharField(max_length=30)),
            ],
        ),
    ]
