# Generated by Django 5.1 on 2024-10-15 04:52

from django.db import migrations

#def create_data(apps,schema_editor):
    

class Migration(migrations.Migration):

    dependencies = [
    ]

   # operations = [
    #]
