# Generated by Django 5.1 on 2024-10-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'employees',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('them', models.CharField(max_length=30)),
                ('requesttype', models.CharField(max_length=30)),
                ('priority', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('responsibleemployee', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'requests',
                'managed': True,
            },
        ),
    ]
