services:
  pgdb:
    image: postgres:16
    container_name: RequestSite
    #volumes:
    #- C:\Users\user\Desktop\pgdata:/var/lib/postgresql/data
    # - './config:/docker-entrypoint-imitdb.d'   инициализация shell скриптов
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "PGDBRequestSite"

    network_mode: "host"
    ports:
      - "5432:5432"
