services:
  pgdb:
    image: postgres:16
    container_name: RequestSite
    volumes:
      - /home/user/request_project/pgdata:/var/lib/postgresql/data
      # - './config:/docker-entrypoint-imitdb.d'   инициализация shell скриптов
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "PGDBRequestSite"

    network_mode: "host"
    ports:
      - "5433:5432"