services:
  db_auth:
    container_name: db_auth
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "RequestSite"
    image: postgres:14.3-alpine

