services:
  db:
    image: postgres:16
    container_name: RequestSite
    volumes:
      - './config/postgresql:/docker-entrypoint-imitdb.d'       #инициализация shell скриптов
    ports:
      - "4321:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "RequestSite"
